### ISSUE TITLE
Add a way for moderators to call a match for either team

### ISSUE THREAD

**Issue by red031000** [TwitchPlaysPokemon/public#105]
for example: if the emulator crashes just before pbrEngine gets the result, but after all the pokemon of one team has fainted, rather than having to do the whole match again, it'd probably be better if a moderator was able to call the match in the opponent's favour and have that as the result, it also could be helpful with debugging new features etc.

**Comment by Felk** [comment]
if the match straight out crashed, do you mean retroactively changing the result from "draw" to either side and recalculating the results?

**Comment by red031000** [comment]
no the match would restart, which is unfair when the results were just about to be called

**Comment by Felk** [comment]
oh I see, okay that makes sense

**Comment by Felk** [comment]
this says moderators should be able to do it. !revertmatch was operator-only. the !overridematchresult command in https://github.com/TwitchPlaysPokemon/tpp/pull/469 fixes this but also for operators only. Is that ok?

**Comment by chaos-lord** [comment]
op only is fine
