### ISSUE TITLE
If a Pokemon uses Transform overlay shows wrong HP Type 

### ISSUE THREAD

**Issue by Fenris2142** [TwitchPlaysPokemon/public#108]
As seen here... Probably has the same issue with Frustration/Return and other moves like that

[https://twitchplaysleaderboard.info/results/pbr/156578/](https://twitchplaysleaderboard.info/results/pbr/156578/)

**Comment by ghost** [comment]
Hidden Power fixed by https://github.com/TwitchPlaysPokemon/pbrEngine/pull/27/commits/cfdce03b5536e880e9c76aeb60629910f588c9ce
friendship is not copied by transform, so Frustration/Return should already be correct.
