### ISSUE TITLE
Allow multiple pinball entires, persistence across restarts, and stopping pinball with a non-empty queue

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#113]

**Comment by Felk** [comment]
> Allow multiple pinball entires

what does that mean?

**Comment by red031000** [comment]
more than one pinball entry, clearly Kappa

**Comment by Felk** [comment]
but that's how it already works?

**Comment by Felk** [comment]
@chaos-lord is everything resolved now? 

> multiple pinball entires

still not sure what that includes that isn't already present

> stopping pinball with a non-empty queue

It doesn't save the queue across restarts. Is that desirable too?

**Comment by chaos-lord** [comment]
sorry I forgot about this:

> Allow multiple pinball entires 

That means being able to enter several games with 1 command, I did implement it myside but it got caught behind a ton of other stuff and now is probably 1 big conflict

> stopping pinball with a non-empty queue

No longer needed with savestates, as I can just ignore pinball during shut-down now
