### ISSUE TITLE
Fix Inventory message formatting

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#13]
These are common bot responses so it'd be nice to fix them soon.

`tpp @Leonsc12 There are 24 Breaker(s) for sale. 4 for t8. ,17 for t9. ,1 for t10. ,2 for t15.`
`tpp fenris2142 sold 2 Gift Crate(s) for t5. 2 for t5 to Izederch.`

(note, while easy to fix, inventory code is a mess. this is technically doable by a sufficiently brave newb but probably not the best code to teach on)

**Comment by red031000** [comment]
fixed
