### ISSUE TITLE
some PWT teams are never chosen by matchmaker

### ISSUE THREAD

**Issue by wilke-0** [TwitchPlaysPokemon/public#130]
PWT teams with only 3 possible pokemon sets never appeared in pbr since the doubles update (March 2019).

**Comment by ghost** [comment]
[fixed in 319fffb22ab903c0117a058d892de648029732b1](https://github.com/TwitchPlaysPokemon/tpp/commit/319fffb22ab903c0117a058d892de648029732b1)
