### ISSUE TITLE
Expose badge transaction logs with the API

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#16]

**Comment by red031000** [comment]
implemented

**Comment by Felk** [comment]
why

**Comment by red031000** [comment]
?

**Comment by Felk** [comment]
why is the badge log exposed?

**Comment by Felk** [comment]
or rather, what's the reason for this ticket? why is exposing the badge log desirable?

**Comment by Felk** [comment]
I'm removing it again for now in https://github.com/TwitchPlaysPokemon/tpp/pull/481
