### ISSUE TITLE
 Tppsim can copy advanced inputs and send them into the game.

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#18]
Either stop any inputs from simbot or make the conscious decision to allow it to input.

**Comment by red031000** [comment]
I believe m4 wanted to allow sim to input, but didn't want the current setup changed, which is kinda weird since the regex allows some stuff but not others, imo it should be one or the other

**Comment by MathyFurret** [comment]
sim is a troll

**Comment by red031000** [comment]
no u

**Comment by m4-used-rollout** [comment]
Ok, sim is allowed to input exactly as sim already inputs.

**Comment by red031000** [comment]
m4 don't close issues when they're a problem Kappa

**Comment by red031000** [comment]
look sim should be allowed to input freely but have a throttle or smth

**Comment by MathyFurret** [comment]
why has sim ever been allowed to input? do we not have a rule against bots inputting?

**Comment by red031000** [comment]
yes but we also have a rule against bots sending messages to chat

**Comment by MathyFurret** [comment]
yeah and which of these two things was sim's original purpose?

**Comment by red031000** [comment]
both Kappa

**Comment by m4-used-rollout** [comment]
Sim is special and does not intentionally input. Sim has been incidentally inputting since its creation and this is the first I've heard of it being a "problem." This is a non-issue.

**Comment by red031000** [comment]
I'd re-open it if I could but uh... well...
@aaaaaa123456789 give me back my privlidges BabyRage

**Comment by aaaaaa123456789** [comment]
@red031000 make me

**Comment by red031000** [comment]
there's literally nothing I can do Kappa
