### ISSUE TITLE
Make cheerful slots not show failures in the animation

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#22]

**Comment by Felk** [comment]
I'm gonna put this under Todo as it sounds like something people would generally agree with is a good thing to do

**Comment by MathyFurret** [comment]
last time i checked it always truncates the spins to the last 3 before it got one that worked, so it should be easy to simply change this to 1 if desired

**Comment by Felk** [comment]
you are correct, nice.
https://github.com/TwitchPlaysPokemon/tpp/pull/417
