### ISSUE TITLE
Fix queue of 0 in transmute

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#39]
transmute says there are 0 people in front of you in the queue for no real reason, this should be removed.

**Comment by mathfreak231** [comment]
Really the only time the message should be dropped is if the user will transmute _immediately_; i.e. there are no other events in the queue. If the user is the first in line for transmutation but it won't start right away, the message is fine.

**Comment by chaos-lord** [comment]
There's no way to know this due to how the overlay handle the queue.

**Comment by red031000** [comment]
fixed
