### ISSUE TITLE
the core should ignore game affecting inputs from mods that are within 1 second of a previous one 

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#56]
Maybe give some leeway like making it 0.8 seconds to account for ping wierdness.

**Comment by aaaaaa123456789** [comment]
It should be 1.5 to put them in equal standing to regular users. There are
no ping weirdnesses to account for; there won't be any significant
variation in such a tiny timeframe, and anyone who does have ping
fluctuations that wild won't be able to watch the stream in the first place.

**Comment by chaos-lord** [comment]
I thought 1 second rule was 1 second? is it really 1.5?

**Comment by aaaaaa123456789** [comment]
It is 1 second. But mods can't get globalled, and thus they can send 30
inputs per half minute, while regular users can send only 20.

Making the limit 1.5s solves this issue as well.

**Comment by chaos-lord** [comment]
that should be a second, separate, check, as mods should not be disadvantaged either

**Comment by chaos-lord** [comment]
after deliberation, a warning after multiple breaches in a small time period is probably better than a hard stop.

**Comment by aaaaaa123456789** [comment]
Exactly why is it useful to allow mods to input in a way nobody else can?

A warning after "multiple breaches" neither stops it from happening nor it
solves the case where breaches are spaced out.

**Comment by m4-used-rollout** [comment]
Does this ever happen?

Would this system be worth the time developing it?

If the core is given the functionality to discard inputs, will it only affect cheating moderators? Or will it bug out and start discarding inputs from non-cheating moderators or even normal players, possibly affecting the outcomes of PBR matches or runs?

We've used moderator spam (at the behest of the chat) to time inputs for intermission games before. It was fun and frivolous and shouldn't be something we remove. We trust our moderators to police chat. Hopefully we can also trust them not to abuse their power and cheat.

And if they do, then we can't trust them and they should no longer be moderators.

The proposed system is worthless at best and a disaster waiting to happen at worst.

**Comment by chaos-lord** [comment]
due to pressures from all sides, I'm removing this as a non-priority
