### ISSUE TITLE
Incorrect song category display

### ISSUE THREAD

**Issue by ferraro1** [TwitchPlaysPokemon/public#59]
From reyn:
When the song in the lead for bidding is "random song" for the battle category,  overlay displays the song category as betting
 https://www.twitch.tv/videos/386807316?t=156754s
…or it just happened randomly last match for no reason, I am unable to reproduce this. It might have to do with the fact that a random song won during the betting period in which the issue occurred

**Comment by Felk** [comment]
vod dead, ancient issue, I'll just close it
