### ISSUE TITLE
Support occasional in-chat announcements

### ISSUE THREAD

**Issue by ferraro1** [TwitchPlaysPokemon/public#68]
Rough draft:

Every hourly break (or maybe more often?), tpp bot could link to a page on our website, or the public repo, or a relevant reddit thread (like a runs poll or feature announcement like the season of seasons post)

We tend to post important announcements on reddit, but unfortunately way too many players don't reddit and never see them, so this feature would be really nice to have.

It could support expiration dates so when a poll is over it stops linking to it.  It could support weights so important announcements appear more frequently.

Announcements could be added and removed via `!announcements <args>`. The db would store the announcements.

**Comment by chaos-lord** [comment]
Complete.
