### ISSUE TITLE
Set which matchmaker settings files to load from the config file, so I don't need a million branches for testing different layouts 

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#69]

**Comment by ferraro1** [comment]
Isn't this an internal issue? Anyway you can specify a different event for each of your different layouts. Events can override whatever parts of settings.yaml that they want to.  See the event configs

**Comment by chaos-lord** [comment]
That'll do, and this is just a generic todo list as far as I'm concerned. IMO it's better if things are in 1 place.
