### ISSUE TITLE
Subscriber oddity.

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#71]
For some reason, twitch send a fake sub notice at the end of the month, which was caught as intended, but then the _next_ sub from that person failed completely with no message to the user or alert in chat. I have no idea what twitch sent to use for that if anything, and it needs looking into.

**Comment by red031000** [comment]
not sure if this has been fixed or not, IIRC felk changed the subscriber code, so that may have fixed this

**Comment by Felk** [comment]
it is working as well as possible. twitch just sends weird messages. I'll assign this to me as a tracking issue since I am actively monitoring these issues

**Comment by red031000** [comment]
is this still an issue? @Felk

**Comment by Felk** [comment]
Twitch never responded to my ticket, so I suppose we're stuck with what we have. I'll close this
