### ISSUE TITLE
Improve music search results

### ISSUE THREAD

**Issue by ferraro1** [TwitchPlaysPokemon/public#72]
Music searching shows all title name matches before showing any album name matches, judging by the output.  So `Song glover` results in:

`Result #1: My Lover - The Revenge of Shinobi (warning)`
<20 more bad matches>
 `Result #22: Carnival Realm Lobby, Level 1 - Glover (betting)`

**Comment by red031000** [comment]
currently in musiccat names of songs have a higher priority than the games, it might be worth turning that up to equal priority

**Comment by red031000** [comment]
I've given the game the same priority in musiccat-cs, the question is whether we want to do that with the old musiccat, as musiccat-cs will soon replace it

**Comment by chaos-lord** [comment]
If it's truly soon, then it's not worth the testing time, and the switch might break some peoples habits too.

**Comment by evolem** [comment]
In the future, there should be the option to look up _either_ by game or song title with the current `!song` command.  Ex: `!song search title Chemical Plant` ; `!song search game Sonic 2` or whichever syntax would be the best and/or easiest to implement.

**Comment by red031000** [comment]
@chaos-lord it's currently waiting for review by m4, but given how busy they are, I don't know how long it will be until it can be replaced

**Comment by red031000** [comment]
I've made a PR to the old musiccat to make the title and the game have the same priority in search, since it doesn't look like musiccat is going to be switched in the next few days

**Comment by red031000** [comment]
implemented
