### ISSUE TITLE
Move bulk of match settings in the config to the matchmaker config

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#76]
This likely means expanding the scope of the matchmaker config to more easily cover more of the core, like the money rewarding function.

**Comment by ferraro1** [comment]
Again this doesn't really seem like a public issue, but I assume it's best to keep the matchmaker compartmentalized to doing matchmaking.  I really don't think we should expand its scope beyond that.

What we can easily do though, is pass the match portion of the tpp config to the matchmaker, which can then take the appropriate actions necessary as they relate to matchmaking.

**Comment by chaos-lord** [comment]
Like the last tim you said that, I just want the todo list all in 1 place and it also shows when we're working on backend stuff and not just being lazy. 

Also, that suggestion is pointless as the reason I wanted it together was to be able to have bonus/bot bet details tied to event for easier changovers.

**Comment by ferraro1** [comment]
Ok, I must have missed your previous comment then.

I think it does makes sense to bring the bonus and bot bets stuff into the matchmaker events.  Hmm... I'm not sure about what to do with the durations though.  The betting duration is something that might end up being matchmaker dependent actually, if we want less time on a 2v2, or more time on a 4v4.  But the commercial duration is obviously unrelated

**Comment by chaos-lord** [comment]
It was an old now closed issue.

As for commercial duration, the reason I said "bulk" is that a few things, including advert length, will want to stay in global config.

**Comment by ferraro1** [comment]
Sure, it just feels a little weird to have them separated

**Comment by chaos-lord** [comment]
It also feels weird to have some bonus related settings in the global, and some in the matchmaker, and it caused that bug at the start of the bonus-less season because you were unaware of a global config I was using. It makes more sense overall to have all the settings that given 1 thing in the central place. It may be worth expanding matchmaker settings to be full match settings instead if it seems odd for some related settings to be there.

**Comment by Felk** [comment]
I'll close this. any config moving arounds should be a direct requirement from some other issue, not an issue per se
