### ISSUE TITLE
Add mode pair 0 bonus list, and expand mode pairing to allow for any size of combonations.

### ISSUE THREAD

**Issue by chaos-lord** [TwitchPlaysPokemon/public#82]
to cover the doubles/kapow/metronome print problem without actually having to ban it.

**Comment by Felk** [comment]
I don't know if this would need further discussion or be a todo, because I don't know what the "doubles/kapow/metronome print problem" is

**Comment by red031000** [comment]
I'm in charge of PBR and I don't even know wtf this issue is Kappa

**Comment by Felk** [comment]
I'll just close it. can be reopened if it did make sense afterall
